server:
  applicationConnectors:
  - type: http
    port: 7070
    bindHost: 0.0.0.0
  adminConnectors:
  - type: http
    port: 7071
    bindHost: 0.0.0.0

swagger:
  resourcePackage: it.unimore.dipi.openness.producer.resources

myAuth: http://eaa.openness:7080/
myApi: https://eaa.openness:7443/
myWs: wss://eaa.openness:7443/
endpoint: http://eaa.openness:7070/api/tis/event/

#logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: INFO